// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package message

import (
	"qq-bot-backend/api/message"
)

type ControllerV1 struct{}

func NewV1() message.IMessageV1 {
	return &ControllerV1{}
}
