// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "qq-bot-backend/internal/logic/bot"
	_ "qq-bot-backend/internal/logic/cfg"
	_ "qq-bot-backend/internal/logic/codec"
	_ "qq-bot-backend/internal/logic/command"
	_ "qq-bot-backend/internal/logic/file"
	_ "qq-bot-backend/internal/logic/group"
	_ "qq-bot-backend/internal/logic/list"
	_ "qq-bot-backend/internal/logic/middleware"
	_ "qq-bot-backend/internal/logic/module"
	_ "qq-bot-backend/internal/logic/namespace"
	_ "qq-bot-backend/internal/logic/process"
	_ "qq-bot-backend/internal/logic/third-party"
	_ "qq-bot-backend/internal/logic/token"
	_ "qq-bot-backend/internal/logic/user"
)
