// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "he3-bot/internal/logic/bot"
	_ "he3-bot/internal/logic/cfg"
	_ "he3-bot/internal/logic/middleware"
)
