// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Whitelist is the golang structure of table whitelist for DAO operations like Where/Data.
type Whitelist struct {
	g.Meta    `orm:"table:whitelist, do:true"`
	ListName  interface{} //
	Namespace interface{} //
	ListJson  interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
