// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package command

import (
	"qq-bot-backend/api/command"
)

type ControllerV1 struct{}

func NewV1() command.ICommandV1 {
	return &ControllerV1{}
}
