// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"time"
)

type (
	ICfg interface {
		IsEnabledDebug(ctx context.Context) bool
		GetDebugToken(ctx context.Context) string
		GetRetryIntervalMilliseconds(ctx context.Context) time.Duration
	}
)

var (
	localCfg ICfg
)

func Cfg() ICfg {
	if localCfg == nil {
		panic("implement not found for interface ICfg, forgot register?")
	}
	return localCfg
}

func RegisterCfg(i ICfg) {
	localCfg = i
}
