// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IGroup interface {
		AddApprovalProcessWithRes(ctx context.Context, groupId int64, processName string, args ...string)
		RemoveApprovalProcessWithRes(ctx context.Context, groupId int64, processName string, args ...string)
		GetApprovalProcess(ctx context.Context, groupId int64) (process map[string]any)
		GetApprovalWhitelists(ctx context.Context, groupId int64) (whitelists map[string]any)
		GetApprovalBlacklists(ctx context.Context, groupId int64) (blacklists map[string]any)
		GetApprovalRegexp(ctx context.Context, groupId int64) (exp string)
		GetApprovalIsAutoPass(ctx context.Context, groupId int64) (yes bool)
		BindNamespaceWithRes(ctx context.Context, groupId int64, namespace string)
		UnbindWithRes(ctx context.Context, groupId int64)
		QueryGroupWithRes(ctx context.Context, groupId int64)
		ExportGroupMemberListWithRes(ctx context.Context, groupId int64, listName string)
		AddKeywordProcessWithRes(ctx context.Context, groupId int64, processName string, args ...string)
		RemoveKeywordProcessWithRes(ctx context.Context, groupId int64, processName string, args ...string)
		GetKeywordProcess(ctx context.Context, groupId int64) (process map[string]any)
		GetKeywordWhitelists(ctx context.Context, groupId int64) (whitelists map[string]any)
		GetKeywordBlacklists(ctx context.Context, groupId int64) (blacklists map[string]any)
		GetKeywordReplyList(ctx context.Context, groupId int64) (listName string)
		SetLogLeaveListWithRes(ctx context.Context, groupId int64, listName string)
		RemoveLogLeaveListWithRes(ctx context.Context, groupId int64)
		GetLogLeaveList(ctx context.Context, groupId int64) (listName string)
	}
)

var (
	localGroup IGroup
)

func Group() IGroup {
	if localGroup == nil {
		panic("implement not found for interface IGroup, forgot register?")
	}
	return localGroup
}

func RegisterGroup(i IGroup) {
	localGroup = i
}
