// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IList interface {
		GetListData(ctx context.Context, listName string) (listMap map[string]any)
		AppendListData(ctx context.Context, listName string, newMap map[string]any) (n int, err error)
		AddListReturnRes(ctx context.Context, listName, namespace string)
		RemoveListReturnRes(ctx context.Context, listName string)
		ExportListReturnRes(ctx context.Context, listName string)
		QueryListLenReturnRes(ctx context.Context, listName string)
		QueryListReturnRes(ctx context.Context, listName string, keys ...string)
		AddListDataReturnRes(ctx context.Context, listName, key string, value ...string)
		RemoveListDataReturnRes(ctx context.Context, listName, key string)
		ResetListDataReturnRes(ctx context.Context, listName string)
		SetListDataReturnRes(ctx context.Context, listName, newListStr string)
		AppendListDataReturnRes(ctx context.Context, listName, newListStr string)
	}
)

var (
	localList IList
)

func List() IList {
	if localList == nil {
		panic("implement not found for interface IList, forgot register?")
	}
	return localList
}

func RegisterList(i IList) {
	localList = i
}
