// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	INamespace interface {
		IsNamespaceExist(ctx context.Context, namespace string) (yes bool)
		IsNamespaceOwnerOrAdmin(ctx context.Context, namespace string, userId int64) (yes bool)
		AddNewNamespace(ctx context.Context, namespace string)
		RemoveNamespace(ctx context.Context, namespace string)
		QueryNamespace(ctx context.Context, namespace string)
		QueryOwnNamespace(ctx context.Context, userId int64)
		AddNamespaceAdmin(ctx context.Context, namespace string, userId int64)
		RemoveNamespaceAdmin(ctx context.Context, namespace string, userId int64)
		ResetNamespace(ctx context.Context, namespace, option string)
	}
)

var (
	localNamespace INamespace
)

func Namespace() INamespace {
	if localNamespace == nil {
		panic("implement not found for interface INamespace, forgot register?")
	}
	return localNamespace
}

func RegisterNamespace(i INamespace) {
	localNamespace = i
}
