// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	INamespace interface {
		IsNamespaceOwnerOrAdmin(ctx context.Context, namespace string, userId int64) (yes bool)
		AddNewNamespaceWithRes(ctx context.Context, namespace string)
		RemoveNamespaceWithRes(ctx context.Context, namespace string)
		QueryNamespaceWithRes(ctx context.Context, namespace string)
		QueryOwnNamespaceWithRes(ctx context.Context)
		AddNamespaceAdminWithRes(ctx context.Context, namespace string, userId int64)
		RemoveNamespaceAdminWithRes(ctx context.Context, namespace string, userId int64)
		ResetNamespaceAdminWithRes(ctx context.Context, namespace string)
		AddNamespaceList(ctx context.Context, namespace, listName string)
		RemoveNamespaceList(ctx context.Context, namespace, listName string)
		GetNamespaceList(ctx context.Context, namespace string) (lists map[string]any)
	}
)

var (
	localNamespace INamespace
)

func Namespace() INamespace {
	if localNamespace == nil {
		panic("implement not found for interface INamespace, forgot register?")
	}
	return localNamespace
}

func RegisterNamespace(i INamespace) {
	localNamespace = i
}
