// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

type (
	IState interface {
		IsBotProcess() bool
		PauseBotProcess() bool
		ContinueBotProcess() bool
	}
)

var (
	localState IState
)

func State() IState {
	if localState == nil {
		panic("implement not found for interface IState, forgot register?")
	}
	return localState
}

func RegisterState(i IState) {
	localState = i
}
