// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IToken interface {
		IsCorrectToken(ctx context.Context, token string) (yes bool)
		AddNewToken(ctx context.Context, name, token string, owner int64)
		RemoveToken(ctx context.Context, name string)
		QueryToken(ctx context.Context)
	}
)

var (
	localToken IToken
)

func Token() IToken {
	if localToken == nil {
		panic("implement not found for interface IToken, forgot register?")
	}
	return localToken
}

func RegisterToken(i IToken) {
	localToken = i
}
