// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IUser interface {
		QueryUserReturnRes(ctx context.Context, userId int64)
		SystemTrustUserReturnRes(ctx context.Context, userId int64)
		SystemDistrustUserReturnRes(ctx context.Context, userId int64)
		IsSystemTrustUser(ctx context.Context, userId int64) (yes bool)
		GrantOpTokenReturnRes(ctx context.Context, userId int64)
		RevokeOpTokenReturnRes(ctx context.Context, userId int64)
		CouldOpToken(ctx context.Context, userId int64) (yes bool)
		GrantOpNamespaceReturnRes(ctx context.Context, userId int64)
		RevokeOpNamespaceReturnRes(ctx context.Context, userId int64)
		CouldOpNamespace(ctx context.Context, userId int64) (yes bool)
		GrantGetRawMsgReturnRes(ctx context.Context, userId int64)
		RevokeGetRawMsgReturnRes(ctx context.Context, userId int64)
		CouldGetRawMsg(ctx context.Context, userId int64) (yes bool)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
