// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IUser interface {
		IsSystemTrustUser(ctx context.Context, userId int64) (yes bool)
		SystemTrustUser(ctx context.Context, userId int64)
		SystemDistrustUser(ctx context.Context, userId int64)
		CouldOperateNamespace(ctx context.Context, userId int64) (yes bool)
		GrantOperateNamespace(ctx context.Context, userId int64)
		RevokeOperateNamespace(ctx context.Context, userId int64)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
