// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// crontabDao is the data access object for the table crontab.
// You can define custom methods on it to extend its functionality as needed.
type crontabDao struct {
	*internal.CrontabDao
}

var (
	// Crontab is a globally accessible object for table crontab operations.
	Crontab = crontabDao{internal.NewCrontabDao()}
)

// Add your custom methods and functionality below.
