// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// groupDao is the data access object for the table group.
// You can define custom methods on it to extend its functionality as needed.
type groupDao struct {
	*internal.GroupDao
}

var (
	// Group is a globally accessible object for table group operations.
	Group = groupDao{internal.NewGroupDao()}
)

// Add your custom methods and functionality below.
