// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// internalListDao is internal type for wrapping internal DAO implements.
type internalListDao = *internal.ListDao

// listDao is the data access object for table list.
// You can define custom methods on it to extend its functionality as you wish.
type listDao struct {
	internalListDao
}

var (
	// List is globally public accessible object for table list operations.
	List = listDao{
		internal.NewListDao(),
	}
)

// Fill with you ideas below.
