// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// listDao is the data access object for the table list.
// You can define custom methods on it to extend its functionality as needed.
type listDao struct {
	*internal.ListDao
}

var (
	// List is a globally accessible object for table list operations.
	List = listDao{internal.NewListDao()}
)

// Add your custom methods and functionality below.
