// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// internalNamespaceDao is internal type for wrapping internal DAO implements.
type internalNamespaceDao = *internal.NamespaceDao

// namespaceDao is the data access object for table namespace.
// You can define custom methods on it to extend its functionality as you wish.
type namespaceDao struct {
	internalNamespaceDao
}

var (
	// Namespace is globally public accessible object for table namespace operations.
	Namespace = namespaceDao{
		internal.NewNamespaceDao(),
	}
)

// Fill with you ideas below.
