// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// namespaceDao is the data access object for the table namespace.
// You can define custom methods on it to extend its functionality as needed.
type namespaceDao struct {
	*internal.NamespaceDao
}

var (
	// Namespace is a globally accessible object for table namespace operations.
	Namespace = namespaceDao{internal.NewNamespaceDao()}
)

// Add your custom methods and functionality below.
