// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// tokenDao is the data access object for the table token.
// You can define custom methods on it to extend its functionality as needed.
type tokenDao struct {
	*internal.TokenDao
}

var (
	// Token is a globally accessible object for table token operations.
	Token = tokenDao{internal.NewTokenDao()}
)

// Add your custom methods and functionality below.
