// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// internalTokenDao is internal type for wrapping internal DAO implements.
type internalTokenDao = *internal.TokenDao

// tokenDao is the data access object for table token.
// You can define custom methods on it to extend its functionality as you wish.
type tokenDao struct {
	internalTokenDao
}

var (
	// Token is globally public accessible object for table token operations.
	Token = tokenDao{
		internal.NewTokenDao(),
	}
)

// Fill with you ideas below.
