// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"qq-bot-backend/internal/dao/internal"
)

// internalWhitelistDao is internal type for wrapping internal DAO implements.
type internalWhitelistDao = *internal.WhitelistDao

// whitelistDao is the data access object for table whitelist.
// You can define custom methods on it to extend its functionality as you wish.
type whitelistDao struct {
	internalWhitelistDao
}

var (
	// Whitelist is globally public accessible object for table whitelist operations.
	Whitelist = whitelistDao{
		internal.NewWhitelistDao(),
	}
)

// Fill with you ideas below.
