// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Whitelist is the golang structure for table whitelist.
type Whitelist struct {
	ListName  string      `json:"list_name"  ` //
	Namespace string      `json:"namespace"  ` //
	ListJson  string      `json:"list_json"  ` //
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
	DeletedAt *gtime.Time `json:"deleted_at" ` //
}
